Multi subgraphs
thebadge/thebadge-sdk pull request #20
Opened 2023-09-25 15:11 UTC by ramabit

# Description

Generating separated subgraphs for dev, staging and prod in order to use and test different queries on different envs.

2023-09-26 12:12 UTC, Agupane requested changes
Lets use this opportunity to update some docs on the readme

2023-09-26 12:12 UTC, Agupane commented on README.md
>        token: '00000000000000',
this should be replace by apiKey

2023-09-26 12:12 UTC, Agupane commented on README.md
>        // your provider token
this should be:
```your infura/alchemy apiKey```

2023-09-26 14:37 UTC, ramabit commented on README.md
>        token: '00000000000000',
done

2023-09-26 14:37 UTC, ramabit commented on README.md
>        // your provider token
done

2023-09-27 12:42 UTC, Agupane approved these changes

2023-09-27 13:06 UTC, merged